export const VALIDATION = {
  PATTERNS: {
    NUMERIC: /^[0-9]+$/,
    DAY: /^[0-9]{1,2}$/,
    YEAR: /^[0-9]{4}$/,
  },
  DAY_MIN: 1,
  DAY_MAX: 31,
  ROOM_MIN: 1,
  ROOM_MAX: 9999,
  ERROR_KEYS: {
    REQUIRED: 'VALIDATION.REQUIRED',
    INVALID_FORMAT: 'VALIDATION.INVALID_FORMAT',
    OUT_OF_RANGE: 'VALIDATION.OUT_OF_RANGE',
  },
} as const;
